export const HITOS = [
    { id: 'legado-intranet', txt: 'intranet', proy: 'legado', tipo: 'legacy', f: '2024-01-15',
        fecha: 'sexenios anteriores · sin fecha',
        motivo: 'La intranet heredada. Lleva años corriendo y en este sexenio no se le tocó una línea: se releva entera con la nueva de diciembre.' },
    { id: 'legado-colibri', txt: 'colibrí', proy: 'legado', tipo: 'legacy', f: '2024-03-15',
        fecha: 'sexenios anteriores · sin fecha',
        motivo: 'El colibrí de sexenios anteriores. El nombre se conservó, pero el de 2026 es un proyecto nuevo: no comparte código con este.' },
    { id: 'gitlab', txt: 'GitLab del instituto', proy: 'infra', tipo: 'momento', f: '2024-12-18',
        fecha: '18 dic 2024',
        motivo: 'El GitLab self-hosted. Hoy tiene 92 proyectos; el más viejo es de esta fecha. Ahí nacieron sieej y mapalab, y ahí sigue intranet.' },
    { id: 'f-sieej-01', txt: 'sieej · 0.1', proy: 'sieej', tipo: 'feature', de: 'sieej', f: '2025-01-20',
        fecha: '20 ene 2025',
        motivo: 'Primer registro del proyecto: React, Vite, Tailwind y los mockups de login y home, en GitLab.' },
    { id: 'f-mapalab-01', txt: 'mapalab · 0.1', proy: 'mapalab', tipo: 'feature', de: 'mapalab', f: '2025-08-10',
        fecha: '10 ago 2025',
        motivo: 'Primer registro del proyecto: estructura básica del visor en React y los primeros componentes de mapa.' },
    { id: 'igibot', txt: 'IGIBot', proy: 'igibot', tipo: 'muerto', f: '2025-11-10',
        fecha: '10 nov 2025 — 15 dic 2025',
        motivo: 'Chatbot agéntico sobre estadística, geografía e indicadores de Jalisco. Fue el primer repo de la organización en GitHub. Su desarrollo principal murió; lo que sobrevivió se rehízo desde cero como agent.' },
    { id: 'github', txt: 'salto a GitHub', proy: 'infra', tipo: 'momento', f: '2025-11-10',
        fecha: '10 nov 2025 — 24 abr 2026',
        motivo: 'La organización abre con IGIBot y los repos se mudan uno por uno: huachicol el 13 nov 2025, sieej el último el 24 abr 2026. El historial no viajó. intranet se quedó en GitLab.' },
    { id: 'f-mariachi-01', txt: 'mariachi · 0.1', proy: 'mariachi', tipo: 'feature', de: 'mariachi', f: '2026-01-26',
        fecha: '26 ene 2026',
        motivo: 'Primer registro: nace el monorepo con API FastAPI, sitio público y CMS bajo un solo Compose.' },
    { id: 'dataengine-1', txt: 'dataengine 1', proy: 'dataengine', tipo: 'mayor', f: '2026-02-25',
        fecha: '25 feb 2026',
        motivo: 'Cluster PostgreSQL con réplica, SSL obligatorio y respaldos diarios al Acervo.' },
    { id: 'geoserver-1', txt: 'geoserver 1', proy: 'sextante', tipo: 'mayor', f: '2026-02-25',
        fecha: '25 feb 2026',
        motivo: 'Primer despliegue a producción. En esta fecha el servicio se llamaba geoserver: el nombre sextante llega hasta julio.' },
    { id: 'gateway-1', txt: 'gateway-hub 1', proy: 'gateway-hub', tipo: 'mayor', f: '2026-03-13',
        fecha: '13 mar 2026',
        motivo: 'El nginx de entrada toma el ruteo de todo el ecosistema.' },
    { id: 'mapalab-1', txt: 'mapalab 1', proy: 'mapalab', tipo: 'mayor', f: '2026-03-27',
        fecha: '27 mar 2026',
        motivo: 'El visor sale estable: descarga de capas, exportación con leyendas y capas temporales.' },
    { id: 'lanz-mapalab', txt: 'MapaLab', proy: 'mapalab', tipo: 'lanzamiento', f: '2026-04-16',
        fecha: '16 abr 2026',
        motivo: 'Lanzamiento oficial en Guadalajara. Nueve temas y 99 capas de los 125 municipios, con datos demográficos desde 1940. El único lanzamiento público del ecosistema.' },
    { id: 'f-agent-01', txt: 'agent · 0.1', proy: 'agent', tipo: 'feature', de: 'agent', f: '2026-05-05',
        fecha: '5 mayo 2026',
        motivo: 'Primer registro del heredero de IGIBot, reescrito por completo.' },
    { id: 'agent', txt: 'agent', proy: 'agent', tipo: 'joven', naceDe: 'igibot', leyenda: 'lo hereda', f: '2026-05-05',
        fecha: 'sin versión mayor',
        motivo: 'Asistente conversacional sobre agentes LLM que integra fuentes por MCP: SQL, documentos e imágenes. Es de solo lectura para el ecosistema.' },
    { id: 'colibri', txt: 'colibrí', proy: 'colibri', tipo: 'joven', naceDe: 'legado-colibri',
        leyenda: 'mismo nombre, todo nuevo', f: '2026-05-07', fecha: '7 mayo 2026',
        motivo: 'El sistema de reportes del ecosistema. Vive dentro de mariachi pero se comporta como producto propio: tiene su widget, su API de llaves y su bandeja.' },
    { id: 'f-colibri-widget', txt: 'colibrí · Widget embebible', proy: 'colibri', tipo: 'feature', de: 'colibri',
        f: '2026-05-07', fecha: '7 mayo 2026',
        motivo: 'Un script que cualquier sistema monta para abrir una incidencia sin salir de su pantalla. Framework-agnóstico.' },
    { id: 'minerva', txt: 'minerva', proy: 'minerva', tipo: 'joven', f: '2026-05-14',
        fecha: 'v0.5.0 · sin versión mayor',
        motivo: 'El SSO institucional: identidad, autenticación y permisos. No es repo nuestro — se consume su main y la integración se registra de nuestro lado.' },
    { id: 'mariachi-1', txt: 'mariachi 1', proy: 'mariachi', tipo: 'mayor', f: '2026-05-14',
        fecha: '14 mayo 2026',
        motivo: 'Primera versión estable en producción; desde aquí el versionado es de producción.' },
    { id: 'godin', txt: 'godin', proy: 'godin', tipo: 'muerto', f: '2026-06-05', fecha: '5 jun 2026',
        motivo: 'Sistema interno con salida propia a internet, sin pasar por el gateway. Murió: ya no se desarrolla.' },
    { id: 'f-catalogo', txt: 'mapalab · Catálogo de capas', proy: 'mapalab', tipo: 'feature', de: 'mapalab',
        f: '2026-06-08', fecha: '8 jun 2026',
        motivo: 'El catálogo público de capas: endpoints /catalogo/capas y su tarjeta propia, administrable desde el CMS.' },
    { id: 'f-vine-01', txt: 'vine · 0.1', proy: 'vine', tipo: 'feature', de: 'vine', f: '2026-06-16',
        fecha: '16 jun 2026',
        motivo: 'Primer registro: scaffolding y modelo de datos de asistencias, con la BD ZKTeco simulada.' },
    { id: 'mirador', txt: 'mirador', proy: 'mirador', tipo: 'joven', f: '2026-07-02', fecha: 'sin versión mayor',
        motivo: 'Laboratorio de datos y visualizaciones del instituto.' },
    { id: 'f-portal-web', txt: 'mariachi · Portal público', proy: 'mariachi', tipo: 'feature', de: 'mariachi',
        muerto: true, f: '2026-07-03', fecha: 'congelado',
        motivo: 'mariachi nació siendo el portal: su base se llamaba iieg_portal hasta el 3 de julio de 2026. Su web/ quedó congelado cuando sitio2026 tomó el rol del portal público.' },
    { id: 'acervo-2', txt: 'acervo 2', proy: 'acervo', tipo: 'mayor', f: '2026-07-21', fecha: '21 jul 2026',
        motivo: 'Termina la migración de MinIO a SeaweedFS. Se va la consola web: todo por mc y weed shell.' },
    { id: 'f-ontoy', txt: 'huachicol · Contrato /ontoy', proy: 'huachicol', tipo: 'feature', de: 'huachicol',
        f: '2026-07-21', fecha: '21 jul 2026',
        motivo: 'Cada servicio declara su versión, su estado y su nodo en un solo endpoint. Es lo que permitió apagar Prometheus y Grafana.' },
    { id: 'f-alertas', txt: 'huachicol · Alertas a Discord', proy: 'huachicol', tipo: 'feature', de: 'huachicol',
        f: '2026-07-21', fecha: '21 jul 2026',
        motivo: 'Las alertas dejan de pasar por Alertmanager y salen directo a Discord desde el monitor.' },
    { id: 'huachicol-2', txt: 'huachicol 2', proy: 'huachicol', tipo: 'mayor', f: '2026-07-21', fecha: '21 jul 2026',
        motivo: 'Se apaga el stack de observabilidad; el repo queda como monitor ligero.' },
    { id: 'f-api', txt: 'gateway-hub · Prefijo /api/mariachi', proy: 'gateway-hub', tipo: 'feature', de: 'gateway-hub',
        f: '2026-07-22', fecha: '22 jul 2026',
        motivo: 'El prefijo de la API cambia en dos fases, con inventario de todo lo que apuntaba al viejo.' },
    { id: 'identidad', txt: 'identidad', proy: 'identidad', tipo: 'joven', naceDe: 'guidelines', leyenda: 'lo absorbe',
        f: '2026-07-28', fecha: '28 jul 2026',
        motivo: 'El módulo que administra la identidad visual multi-marca. Absorbió al design system: por eso guidelines-iieg se archivó al día siguiente.' },
    { id: 'f-numeralia', txt: 'mariachi · Numeralia dinámica', proy: 'mariachi', tipo: 'feature', de: 'mariachi',
        f: '2026-07-29', fecha: '29 jul 2026',
        motivo: 'Estadísticas dinámicas de metadatos de capas, calculadas en dataengine y servidas por mariachi al visor.' },
    { id: 'guidelines', txt: 'guidelines-iieg', proy: 'heredado', tipo: 'muerto', f: '2026-07-29', fecha: '29 jul 2026',
        motivo: 'Se archiva en solo lectura: el módulo Identidad del CMS absorbió el design system.' },
    { id: 'f-mcp', txt: 'mapalab · Servidor MCP', proy: 'mapalab', tipo: 'feature', de: 'mapalab',
        f: '2026-07-30', fecha: '30 jul 2026',
        motivo: 'El visor expone un servidor MCP: sus capas y su catálogo quedan consultables por herramientas de IA.' },
    { id: 'sextante-2', txt: 'sextante 2', proy: 'sextante', tipo: 'mayor', naceDe: 'geoserver-1',
        leyenda: 'se renombra', antes: 'geoserver', f: '2026-07-31', fecha: '31 jul 2026',
        motivo: 'El servicio deja de llamarse geoserver: cambian contenedores, red y la URL pública. Mismo software, nombre nuevo.' },
    { id: 'sitio2026', txt: 'sitio2026', proy: 'sitio2026', tipo: 'mayor', naceDe: 'f-portal-web',
        leyenda: 'lo sucede', f: '2026-07-31', fecha: '31 jul 2026',
        motivo: 'El portalito toma el location / del gateway, con iieg.jalisco.gob.mx como dominio objetivo. sitio2026 y portalito son el mismo.' },
    { id: 'espejo', txt: 'espejo de Proxmox', proy: 'infra', tipo: 'momento', f: '2026-08-03', fecha: '3 ago 2026',
        motivo: 'El Proxmox del instituto pasa a espejo multi-nodo: una VM por rol S1-S5. Ahí vive también el runner de CI self-hosted.' },
    { id: 'f-colibri-huespedes', txt: 'colibrí · Cinco huéspedes', proy: 'colibri', tipo: 'feature', de: 'colibri',
        f: '2026-08-10', fecha: '10 ago 2026',
        motivo: 'La adopción: cinco sistemas del ecosistema montan el widget. Falta el hardening H4.' },
    { id: 'mariachi-2', txt: 'mariachi 2', proy: 'mariachi', tipo: 'mayor', f: '2026-08-10', fecha: '10 ago 2026',
        motivo: 'El feature fuerte del ciclo: la identidad se va a minerva. Retira su login propio y la autorización deja de mirar el rol.' },
    { id: 'sieej-2', txt: 'sieej 2', proy: 'sieej', tipo: 'mayor', f: '2026-08-10', fecha: '10 ago 2026',
        motivo: 'Su pantalla de login se va a minerva; no se puede desplegar sin mariachi 2.' },
    { id: 'wacha', txt: 'wacha', proy: 'wacha', tipo: 'mayor', antes: 'frigate', f: '2026-08-10', fecha: '10 ago 2026',
        motivo: 'El repo se transfiere y se renombra: se llamaba frigate. Comparte VM con vine desde ese mismo día.' },
    { id: 'f-identidad-tokens', txt: 'identidad · Tokens y temas', proy: 'identidad', tipo: 'feature', de: 'identidad',
        f: '2026-08-17', fecha: '17 ago 2026',
        motivo: 'Emite el theme.qss que lee el complemento de QGIS y los tokens que consumen los frontends. La marca deja de estar escrita en el código.' },
    { id: 'f-qgis', txt: 'mapalab · Complemento de QGIS', proy: 'mapalab', tipo: 'feature', de: 'mapalab',
        f: '2026-08-17', fecha: '17 ago 2026',
        motivo: 'El complemento de QGIS con el catálogo del visor. Vive en su propio repo por comodidad de empaquetado, pero es un feature de mapalab.' },
    { id: 'f-sidecar', txt: 'huachicol · Sidecar de encargo', proy: 'huachicol', tipo: 'feature', de: 'huachicol',
        f: '2026-08-26', fecha: '26 ago 2026',
        motivo: 'Un /ontoy prestado para los servicios que no pueden exponer el suyo, como sitio2026.' },
    { id: 'f-uptime', txt: 'huachicol · Uptime de 24 horas', proy: 'huachicol', tipo: 'feature', de: 'huachicol',
        f: '2026-08-26', fecha: '26 ago 2026',
        motivo: 'El /api/status publica las 24 horas de cada servicio comprimidas en tramos, en vez de un solo número.' },
    { id: 'f-nodos', txt: 'huachicol · Mapa de nodos', proy: 'huachicol', tipo: 'feature', de: 'huachicol',
        f: '2026-08-27', fecha: '27 ago 2026',
        motivo: 'El /ontoy pasa a hablar de la máquina y no solo del servicio. /api/nodos agrupa los servicios por servidor y el CMS lo dibuja como mapa.' },
    { id: 'f-temp', txt: 'huachicol · Temperatura del CPU', proy: 'huachicol', tipo: 'feature', de: 'huachicol',
        f: '2026-08-28', fecha: '28 ago 2026',
        motivo: 'El nodo reporta la temperatura cuando el equipo la expone, como lista de sensores.' },
    { id: 'dns', txt: 'DNS local del instituto', proy: 'infra', tipo: 'momento', f: '2026-08-28', fecha: '28 ago 2026',
        motivo: 'portalito.iieg e intranet.iieg en el DNS del AD. Los dos apuntan al hipervisor de Proxmox, que enruta por server_name a la VM que toca.' },
    { id: 'f-selector', txt: 'mapalab · Selector de municipios', proy: 'mapalab', tipo: 'feature', de: 'mapalab',
        beta: true, f: '2026-08-28', fecha: 'en desarrollo',
        motivo: 'El selector de municipios del visor. Es lo que se está terminando ahora: todavía no sale a público.' },
    { id: 'intranet-1', txt: 'intranet 1', proy: 'intranet', tipo: 'porllegar', naceDe: 'legado-intranet',
        leyenda: 'lo releva', f: '2026-12-15', fecha: 'mediados de dic 2026',
        motivo: 'La intranet nueva, la que vive en GitLab, releva a la de sexenios anteriores. Hoy se llega por intranet.iieg.' },
    { id: 'vine-1', txt: 'vine 1', proy: 'vine', tipo: 'porllegar', f: '2026-12-20', fecha: 'sin fecha comprometida',
        motivo: 'Deja de ser sistema aparte: las asistencias se administran desde el CMS.' },
    { id: 'f-minerva-sub', txt: 'minerva · Subdominio propio', proy: 'minerva', tipo: 'feature', de: 'minerva',
        beta: true, f: '2027-03-01', fecha: 'sin fecha comprometida',
        motivo: 'Sacar a minerva de la ruta compartida y darle host propio. Plan escrito, sin fecha.' },
    { id: 'sitio-viejo', txt: 'apagado del sitio viejo', proy: 'heredado', tipo: 'momento', f: '2027-06-01',
        fecha: '2027 · sin fecha',
        motivo: 'El apagado definitivo del portal heredado. Su Apache con PHP ya no sirve nada desde marzo de 2026, pero la VM y el MySQL siguen ahí.' },
];
