name: mariachi-dev

x-logging: &logging
  driver: json-file
  options:
    max-size: "10m"
    max-file: "3"

services:
  postgres:
    container_name: mariachi-postgres-dev
    ports:
      - "${POSTGRES_BIND_ADDR:?}:${POSTGRES_PORT:?}:5432"

  redis:
    container_name: mariachi-redis-dev
    ports:
      - "${REDIS_BIND_ADDR:?}:${REDIS_PORT:?}:6379"

  api:
    build:
      target: development
    image: mariachi-api-dev
    container_name: mariachi-api-dev
    ports:
      - "${API_BIND_ADDR:?}:${API_PORT:?}:8000"
    env_file:
      - .env.development
    volumes:
      - ./api:/app
      - ./docs/CHANGELOG.md:/app/_docs/CHANGELOG.md:ro
    environment:
      ACERVO_ENDPOINT: ${ACERVO_ENDPOINT:?}
      ACERVO_PUBLIC_ENDPOINT: ${ACERVO_PUBLIC_ENDPOINT?}
      ACERVO_USE_SSL: ${ACERVO_USE_SSL:?}
      ACERVO_VERIFY_SSL: ${ACERVO_VERIFY_SSL:?}

  admin:
    build:
      context: ./admin
      dockerfile: Dockerfile.dev
    image: mariachi-admin-dev
    container_name: mariachi-admin-dev
    working_dir: /app
    ports:
      - "${ADMIN_BIND_ADDR:?}:${ADMIN_PORT:?}:3011"
    volumes:
      - ./admin:/app
      - admin_node_modules:/app/node_modules
    env_file:
      - .env.development
    environment:
      VITE_PORT: "3011"
      VITE_GOOGLE_ANALYTICS_ID: ${VITE_GOOGLE_ANALYTICS_ID?}
      VITE_MAPALAB_PROXY_URL: ${VITE_MAPALAB_PROXY_URL:?}
      VITE_CARTO_API_KEY: ${VITE_CARTO_API_KEY?}
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - mariachi_network
    logging: *logging

volumes:
  admin_node_modules:
