# syntax=docker/dockerfile:1
FROM node:26-alpine

WORKDIR /app

COPY package*.json ./

RUN --mount=type=cache,target=/root/.npm npm install

EXPOSE 3011

CMD ["npm", "run", "dev", "--", "--host", "0.0.0.0"]
